### ISSUE TITLE
_load_from_ifs error on i_11011.ifs

### ISSUE THREAD

**Issue by aixxe** [mon/infinitas_decrypt#1]
Had an issue using this today which seemed to always occur on the same file.

```
i_15018.ifs
i_18004.ifs
i_16004.ifs
i_18065.ifs
i_13053.ifs
i_13021.ifs
i_11011.ifs
 22%|██████████████▏                                                 | 4/18 [00:12<00:44,  3.18s/it
 Traceback (most recent call last):                                             | 0/6 [00:00<?, ?it/s]
  File "iidx_cloud_decrypt.py", line 114, in <module>
    main()
  File "iidx_cloud_decrypt.py", line 59, in main
    ifs.extract(use_cache = False, recurse = False, path = dst)
  File "/home/aixxe/.local/lib/python3.7/site-packages/ifstools/ifs.py", line 163, in extract
    f.extract(path, **kwargs)
  File "/home/aixxe/.local/lib/python3.7/site-packages/ifstools/handlers/GenericFile.py", line 25, in extract
    data = self.load(**kwargs)
  File "/home/aixxe/.local/lib/python3.7/site-packages/ifstools/handlers/GenericFile.py", line 31, in load
    return self._load_from_ifs(**kwargs)
TypeError: _load_from_ifs() got an unexpected keyword argument 'use_cache'
```

Managed to get it working after removing the `use_cache` argument from line 59.

```
# ifs.extract(use_cache = False, recurse = False, path = dst)
ifs.extract(recurse = False, path = dst)
```

Very useful project by the way, thank you!

**Comment by mon** [comment]
Hmm, strange, I thought I fixed that. Could you try `pip install ifstools -U` and see if the latest version fixes it?

**Comment by aixxe** [comment]
Tried again but still getting the same error.

https://www.hastebin.com/raw/pibicoseje

Full install and usage log above in case I've missed something. Made sure to clear out anything from `.cache` and `.local` before running.

**Comment by mon** [comment]
Oh right I forgot I monkeypatched it. Should be fixed.
